### ISSUE TITLE
grid pager is not executing

### ISSUE THREAD

**Issue by ghost** [TheNinjaBrotherhood/Grid-Mvc-Ajax-Demo#1]
I run the code yesterday and it was working perfectly fine but now the ajax paging is not working at all.

Appreciate any help in fixing this issue.
Thanks.

**Comment by easlavov** [comment]
Hello! Thanks for writing!

Curious. I recloned the repository just to make sure the demo is working fine. And it is! Try to clone the demo repository in another folder, clear the browser cache, run the project again and see if the issue persists. Other than that, I can't offer much help. :(

If you still have problems, try to debug both on the client and on the server: 1) see if any AJAX calls are made in the Network tab in the Developer Tools in your browser; 2) See if the actions are executed correctly on the server.

Keep me udpated and good luck!

**Comment by ghost** [comment]
Thank you for your prompt replay. 
It seems that the problem was fixed when in I clear the browser history for this demo example. 
In my project it doesn't work, I even used the same version for the grid 1.0.24. but before that I installed the grid.MVC package. maybe this can be the problem. I tried all the solutions I can think of. install the same version for jquery packages and etc. 

The browser developer tool ( console section didn't recognize ) 

In chrome:
home.js:18 Uncaught TypeError: undefined is not a function => when I open this file it highlights this statement $('.grid-mvc').gridmvc();

In Firefox:
TypeError: $(...).gridmvc is not a function home.js:18
ReferenceError: GridMvc is not defined gridmvc-ext.js:2
TypeError: $(...).gridmvc is not a function home.js:18
gridmvc-ext.js:2 Uncaught ReferenceError: GridMvc is not defined

I really appreciate your help.

**Comment by easlavov** [comment]
Hello again!

Components need to be loaded in the correct order. The error you're seeing is due to grid.mvc library not loading correctly.

Take a look at this screenshot and the loading order of components.
![example](https://cloud.githubusercontent.com/assets/4385825/6058134/26cb6aec-ad2d-11e4-806d-70c4f63d42df.png)
The browser first renders the div inside the body. As you can see there is a div with the 'grid-mvc' present. Not a single script has been loaded up to this point. First, jQuery is initialized (and then other unrelated scripts). Immediately the scripts in the GridMvc folder are executed. At this point the $ object is being extended. This allows the gridmvc() function to be called from any jquery object ($jqueryObject.gridmvc()).
Finally, after all libraries have been loaded, the home.js (wher I use the gridmvc() function) is executed.

Make sure everything is loaded in the correct order. I hope it helps.

Don't hesitate to contact me again if you can't fix the issue.

Good luck!
